on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          ssh-key: ${{ secrets.git_ssh_key }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Quarto html render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
      
      - name: Quarto publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
